// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTx7MGJptq_u-dSnLzFgtzeTU9xgQztZU',
    appId: '1:899053633246:web:5aeb9452145d0d07494c4f',
    messagingSenderId: '899053633246',
    projectId: 'rieng-76516',
    authDomain: 'rieng-76516.firebaseapp.com',
    storageBucket: 'rieng-76516.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDGXXNMQjRmR4H65V13IsW4snbyJXH848',
    appId: '1:899053633246:android:ce033071fb074bef494c4f',
    messagingSenderId: '899053633246',
    projectId: 'rieng-76516',
    storageBucket: 'rieng-76516.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTx7MGJptq_u-dSnLzFgtzeTU9xgQztZU',
    appId: '1:899053633246:web:7361acb3189df90e494c4f',
    messagingSenderId: '899053633246',
    projectId: 'rieng-76516',
    authDomain: 'rieng-76516.firebaseapp.com',
    storageBucket: 'rieng-76516.firebasestorage.app',
  );
}
